### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by roamerhappiness** [lambdasoup/watchlater#47]
One second I was adding videos. The next second none of the videos will add anymore. I cleared the data from the app and then tried again, added my YouTube account and still it won't work.

**Comment by roamerhappiness** [comment]
![Screenshot_20191018-013816](https://user-images.githubusercontent.com/55665696/67068759-f9a83300-f148-11e9-939f-9aca77eeebd2.png)

**Comment by maxhille** [comment]
Thanks for the report.

Looks like we hit our YouTube API daily quota on 2019-10-17. After I saw your report, I was able to reproduce it on my personal device. Once I hooked up the dev environment for debugging everything worked again :-/. This indicates a quota problem since the YouTube API docs say that the quota resets "midnight Pacific Time", which actually matches what I observed.

We will have to request a higher quota from YouTube which unfortunately involves a rather elaborate form with lots of typing and stuff but well, that's what weekends are for, right?

**Comment by roamerhappiness** [comment]
You should add a small donate button to your app.

**Comment by maxhille** [comment]
That would involve bundling proprietary Google Play stuff unfortunately. Maybe I'll add a crypto currency donate button to this GitHub repo.

**Comment by maxhille** [comment]
After some waiting, quota has been increased.
